//! A deliberately small recognizer, not a BAT interpreter. Unknown lines fail closed.
use crate::domain::{BatAnalysis, MToolRecipe};
use crate::paths::relative_path;

pub fn generated_launcher_name(name: &str) -> bool {
    matches!(
        name.trim().to_lowercase().as_str(),
        "与工具一同启动.bat" | "start with tool.bat" | "start_with_tool.bat"
    )
}

fn tokens(line: &str) -> std::result::Result<Vec<String>, String> {
    let mut values = Vec::new();
    let mut current = String::new();
    let mut quoted = false;
    let mut active = false;
    for ch in line.chars() {
        match ch {
            '"' => {
                quoted = !quoted;
                active = true;
            }
            ch if ch.is_whitespace() && !quoted => {
                if active {
                    values.push(std::mem::take(&mut current));
                    active = false;
                }
            }
            ch => {
                current.push(ch);
                active = true;
            }
        }
    }
    if quoted {
        return Err("引号不匹配".into());
    }
    if active {
        values.push(current);
    }
    Ok(values)
}

fn clean_path(value: &str) -> std::result::Result<String, String> {
    let path = value.replace('/', "\\");
    let rest = if path.to_lowercase().starts_with("%~dp0") {
        &path[5..]
    } else {
        &path
    };
    if rest.contains('%') || rest.contains('!') {
        return Err("不支持环境变量或动态展开".into());
    }
    // Normalize the harmless double separator often found after %~dp0.
    Ok(if path.to_lowercase().starts_with("%~dp0") {
        format!("%~dp0{}", rest.trim_start_matches('\\'))
    } else {
        path
    })
}

fn under(path: &str, root: &str) -> std::result::Result<String, String> {
    let prefix = format!("{}\\", root.trim_end_matches('\\'));
    let relative = if root == "%~dp0" {
        path.strip_prefix("%~dp0")
            .map(|s| s.trim_start_matches('\\'))
    } else if path
        .get(..prefix.len())
        .is_some_and(|part| part.eq_ignore_ascii_case(&prefix))
    {
        Some(&path[prefix.len()..])
    } else {
        None
    }
    .ok_or("路径不在预期的目录内")?;
    relative_path(relative).map_err(|e| e.to_string())?;
    Ok(relative.replace('\\', "/"))
}

fn recognize(content: &str) -> std::result::Result<MToolRecipe, String> {
    let mut injection: Option<(String, String, String)> = None;
    let mut runtime: Option<(String, String)> = None;
    for (index, raw) in content.trim_start_matches('\u{feff}').lines().enumerate() {
        if raw.len() > 4096 {
            return Err("BAT 行过长，请手工配置启动信息".into());
        }
        let line = raw.trim().trim_start_matches('@').trim();
        let lower = line.to_lowercase();
        if line.is_empty() {
            continue;
        }
        // Metacharacters and expansion syntax are unsupported even inside quotes.
        if line
            .chars()
            .any(|c| matches!(c, '&' | '|' | '<' | '>' | '^' | '!' | '\0'))
        {
            return Err(format!("第 {} 行包含不支持的 shell 语法", index + 1));
        }
        if lower == "rem" || lower.starts_with("rem ") || line.starts_with("::") {
            continue;
        }
        let parts = tokens(line)?;
        let words: Vec<String> = parts.iter().map(|p| p.to_lowercase()).collect();
        let generated_notice = parts.len() == 2
            && words[0] == "echo"
            && [
                "please do not modify this file, it is automatically generated by the mtool.",
                "if you want to package and release the game,",
                "请不要修改该文件",
                "如果你想要打包发布游戏",
            ]
            .iter()
            .any(|prefix| words[1].starts_with(prefix));
        if generated_notice
            || words == ["chcp", "65001"]
            || words == ["echo", "off"]
            || words == ["cd", "/d", "%~dp0"]
        {
            continue;
        }
        if parts.len() == 3 && words[0].replace('/', "\\").ends_with("\\inject.exe") {
            if runtime.is_some() || injection.is_some() {
                return Err("重复或顺序异常的 inject 命令".into());
            }
            injection = Some((
                clean_path(&parts[0])?,
                clean_path(&parts[1])?,
                clean_path(&parts[2])?,
            ));
        } else if parts.len() == 4 && words[0] == "start" && parts[1].is_empty() {
            if injection.is_none() || runtime.is_some() {
                return Err("重复或顺序异常的 runtime 命令".into());
            }
            runtime = Some((clean_path(&parts[2])?, clean_path(&parts[3])?));
        } else {
            return Err(format!(
                "第 {} 行不是已知 MTool 模式：需要人工检查",
                index + 1
            ));
        }
    }
    let (injector, target, loader) = injection.ok_or("未找到 inject.exe 命令")?;
    let (runtime, root) = runtime.ok_or("未找到 MTool / nw runtime 命令")?;
    // Only absolute drive paths or a directory explicitly anchored to the game BAT are understood.
    let drive_root = root.as_bytes().first().is_some_and(u8::is_ascii_alphabetic)
        && root.as_bytes().get(1) == Some(&b':')
        && root.as_bytes().get(2) == Some(&b'\\');
    if !drive_root && !root.starts_with("%~dp0") {
        return Err("MTool root 必须为绝对盘符路径或 %~dp0 路径".into());
    }
    if root.split('\\').any(|part| part == ".." || part == ".") {
        return Err("MTool root 包含相对跳转".into());
    }
    let injector_rel = under(&injector, &root)?;
    if !injector_rel.eq_ignore_ascii_case("loaders/inject.exe") {
        return Err("未知 injector 路径".into());
    }
    let target_rel = under(&target, "%~dp0")?;
    if !target_rel.to_lowercase().ends_with(".exe") {
        return Err("target 不是 EXE".into());
    }
    let loader_rel = under(&loader, &root)?;
    if !loader_rel.to_lowercase().starts_with("loaders/")
        || !loader_rel.to_lowercase().ends_with(".dll")
    {
        return Err("loader 必须是 loaders 目录内的 DLL".into());
    }
    let runtime_rel = under(&runtime, &root)?;
    if !["mtool.exe", "nw.exe"].contains(&runtime_rel.to_lowercase().as_str()) {
        return Err("未知 MTool runtime".into());
    }
    Ok(MToolRecipe {
        target_exe: target_rel,
        loader: loader_rel,
        injector: injector_rel,
        runtime: runtime_rel,
        observed_root: root,
    })
}

pub fn parse_bat(path: &str, content: &str) -> BatAnalysis {
    match recognize(content) {
        Ok(recipe) => BatAnalysis {
            path: path.into(),
            status: "supported".into(),
            recipe: Some(recipe),
            messages: vec![
                "仅分析；未执行 BAT。使用前请确认 target、loader 和共享 MTool 配置。".into(),
            ],
        },
        Err(reason) => BatAnalysis {
            path: path.into(),
            status: "unsupported".into(),
            recipe: None,
            messages: vec![reason],
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn generated_launcher_names_and_official_notices_do_not_enable_arbitrary_bat_commands() {
        assert!(generated_launcher_name("Start With Tool.bat"));
        assert!(generated_launcher_name("与工具一同启动.bat"));
        assert!(!generated_launcher_name("unrelated.bat"));
        let content = format!("{}\n@echo \"Please do not modify this file, it is automatically generated by the MTool. If there is an issue with the path, regenerate it.\"\n@echo \"If you want to package and release the game, check the tool option.\"\n@echo \"请不要修改该文件，文件由工具生成。\"", sample("任意.exe", "mzHook.dll", "MTool.exe"));
        assert!(parse_bat("与工具一同启动.bat", &content).recipe.is_some());
        assert!(parse_bat("test", &format!("{content}\necho anything"))
            .recipe
            .is_none());
        assert!(parse_bat("test", &format!("{content}\n@echo \"Please do not modify this file, it is automatically generated by the MTool. & del x\"")).recipe.is_none());
    }
    fn sample(target: &str, loader: &str, runtime: &str) -> String {
        format!("@chcp 65001\r\n@cd /d \"%~dp0\"\r\n\"E:\\Butter\\Tool\\loaders\\inject.exe\" \"%~dp0\\{target}\" \"E:\\Butter\\Tool\\loaders\\{loader}\"\r\nstart \"\" \"E:\\Butter\\Tool\\{runtime}\" \"E:\\Butter\\Tool\"")
    }
    #[test]
    fn parses_unicode_spaces_and_explicit_loader() {
        let result = parse_bat(
            "与工具一同启动.bat",
            &sample("日文 游戏.exe", "mzHook32.dll", "MTool.exe"),
        );
        let recipe = result.recipe.unwrap();
        assert_eq!(recipe.target_exe, "日文 游戏.exe");
        assert_eq!(recipe.loader, "loaders/mzHook32.dll");
        assert_eq!(recipe.observed_root, "E:\\Butter\\Tool");
    }
    #[test]
    fn supports_bundled_tool_and_nw() {
        let text = sample("bin\\ゲーム.exe", "mzHook.dll", "nw.exe")
            .replace("E:\\Butter\\Tool", "%~dp0Tool");
        let recipe = parse_bat("launch.bat", &text).recipe.unwrap();
        assert_eq!(recipe.target_exe, "bin/ゲーム.exe");
        assert_eq!(recipe.runtime, "nw.exe");
    }
    #[test]
    fn rejects_unknown_commands_expansions_mismatched_roots_and_malformed_recipes() {
        for command in [
            "powershell -NoProfile test",
            "curl example.com",
            "reg add test",
            "del *.exe",
            "format C:",
            "call foo.bat",
            "cmd /c foo",
            "pause",
            "echo %PATH%",
            "set X=1",
        ] {
            assert_eq!(
                parse_bat(
                    "test",
                    &format!(
                        "{}\n{command}",
                        sample("Game.exe", "mzHook.dll", "MTool.exe")
                    )
                )
                .status,
                "unsupported",
                "{command}"
            );
        }
        for name in [
            "Game.exe&del x",
            "Game!x.exe",
            "Game%PATH%.exe",
            "..\\Game.exe",
        ] {
            assert!(parse_bat("test", &sample(name, "mzHook.dll", "MTool.exe"))
                .recipe
                .is_none());
        }
        let text = sample("Game.exe", "mzHook.dll", "MTool.exe");
        for content in [
            text.replace("start \"\"", "start \"title\""),
            text.replace("\\loaders\\mzHook.dll", "\\..\\mzHook.dll"),
            format!("{text}\n{text}"),
            text.replace("\\Tool\\MTool.exe", "\\Else\\MTool.exe"),
            format!("{text}\n\"unfinished"),
            String::new(),
        ] {
            assert!(parse_bat("test", &content).recipe.is_none());
        }
    }
    #[test]
    fn allows_bom_comments_and_does_not_require_game_exe() {
        let text = format!(
            "\u{feff}@echo off\nrem harmless\n:: comment\n{}",
            sample("任意名.exe", "mzHook.dll", "MTool.exe")
        );
        assert!(parse_bat("test", &text).recipe.is_some());
    }

    #[test]
    fn rejects_comment_operators_and_handles_unicode_root_without_panicking() {
        let text = sample("任意名.exe", "mzHook.dll", "MTool.exe");
        assert!(
            parse_bat("test", &format!("rem comment & powershell unsafe\n{text}"))
                .recipe
                .is_none()
        );
        assert!(
            parse_bat("test", &text.replace("E:\\Butter", "E:\\İstanbul 游戏"))
                .recipe
                .is_some()
        );
        // Unicode lowercasing can change byte lengths; mismatched roots must fail without slicing panic.
        let mismatched = text.replace("E:\\Butter", "E:\\İstanbul").replace(
            "E:\\İstanbul\\Tool\\MTool.exe",
            "E:\\i\u{307}stanbul\\Tool\\MTool.exe",
        );
        assert!(parse_bat("test", &mismatched).recipe.is_none());
    }
}
